name: Build & Deploy pip Simple Index

on:
  workflow_dispatch:

permissions:
  contents: write    # for checkout and uploading artifacts
  pages: write       # to deploy GitHub Pages
  id-token: write    # to mint an OIDC token for deploy-pages

jobs:
  publish-index:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the default branch so we have repo context
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Generate PEP 503 “simple” index from release assets
      - name: Generate pip simple index
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const { owner, repo } = context.repo;
            // Fetch all releases via the GitHub API
            const releases = await github.rest.repos.listReleases({ owner, repo });
            const packages = {};
            // Collect all .whl asset URLs, grouped by package name
            for (const release of releases.data) {
              for (const asset of release.assets) {
                if (asset.name.endsWith('.whl')) {
                  const pkg = asset.name.split('-')[0].toLowerCase();
                  packages[pkg] = packages[pkg] || [];
                  packages[pkg].push({ url: asset.browser_download_url, name: asset.name });
                }
              }
            }
            // Build the /simple/ HTML structure
            fs.mkdirSync('simple', { recursive: true });
            let rootHtml = '<!DOCTYPE html><html><body>\n';
            for (const pkg of Object.keys(packages).sort()) {
              rootHtml += `<a href="./${pkg}/">${pkg}</a><br>\n`;
              const pkgDir = `simple/${pkg}`;
              fs.mkdirSync(pkgDir, { recursive: true });
              let pkgHtml = '<!DOCTYPE html><html><body>\n';
              for (const file of packages[pkg]) {
                pkgHtml += `<a href="${file.url}#${file.name}">${file.name}</a><br>\n`;
              }
              pkgHtml += '</body></html>\n';
              fs.writeFileSync(`${pkgDir}/index.html`, pkgHtml);
            }
            rootHtml += '</body></html>\n';
            fs.writeFileSync('simple/index.html', rootHtml);

      # 3. Package the generated index for Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: simple

      # 4. Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
