name: Publish Wheels to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to pull wheels from'
        required: true

# Grant the runner permission to read repo contents and write to Packages
permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Download wheels from release ${{ github.event.inputs.tag }}
        uses: robinraju/release-downloader@v1.12
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.inputs.tag }}
          fileName: '*.whl'
          out-file-path: 'dist'

      - name: List downloaded wheels
        run: ls dist

      - name: Publish wheels to GitHub Packages
        run: |
          python -m pip install --upgrade pip twine
          python -m twine upload \
            --repository-url https://upload.pypi.pkg.github.com/${{ github.repository_owner }} \
            --username __token__ \
            --password ${{ secrets.GITHUB_TOKEN }} \
            dist/*
